### PR TITLE
Create action filter that resolves an IQueryable asynchronously

### PR DESCRIPTION
**Pull request by csantero**
Implements #19 

I'm not really happy with the name of `ResolveAsyncQueryablesAttribute`. Any thoughts?

### CODE REVIEW

**Comment by SphtKr** [comment]
`OptimizeQueryableAttribute`? `QueryableAcceleratorAttribute`? `AsyncQueryResolverAttribute`? Not sure if those are any better, just brainstorming.

**Comment by csantero** [comment]
I think something relating to the word Materialize captures the essence of what we are doing best, but we already have IMaterializer which is something completely different. =P

`FetchAsyncQueryAttribute`? `AsyncQueryFetcherAttribute`? Blah

**Comment by SphtKr** [comment]
"Reify"? That means something specific that I'm still not clear on...I though about using that instead of "materialize" but decided against it in that instance.

**Comment by csantero** [comment]
[The .NET documentation for ToArrayAsync](https://msdn.microsoft.com/en-us/library/dn220247(v=vs.113).aspx) uses the verb "enumerate". How about `AsyncQueryEnumeratorAttribute` or `EnumerateQueriesAsynchronouslyAttribute` or something of that ilk?

**Comment by SphtKr** [comment]
Sure, Enumerate.... EnumerateQueryableAsyncAttribute? Our attributes so far tend to be verbs. Queryable singular, because as an actual attribute it would be applied to the method, which returns one IQueryable. That name to me looks like what it does when it's used to decorate a method:

    [EnumerateQueryableAsync]
    public IQueryable<Model> Get() { }

But I think we've already overthought this. Just pick one, probably.

**Comment by csantero** [comment]
EnumerateQueryableAsyncAttribute it is. New diff is up.

**Pull request merged**
