### PR TITLE
Byte Id Serialization

### PR DESCRIPTION
**Pull request by karlguillotte**
Closes #66 

This pull request allows to have Id of type byte. They will be
serialized properly.

### CODE REVIEW

**Comment by csantero** [comment]
Looks good! Eventually we need a more generic solution that will allow for any primitive type to be used as the ID property, but this is fine for now.

One small nitpick, could you reformat the braces to be in line with the brace style used elsewhere in the project? Allman-style, brace goes on the next line. Thanks

**Comment by karlguillotte** [comment]
I will do Allman-style in the future. 

I agree regarding having a more generic way of doing id serialization. Probably need something similar to the `TypeExtensions`.

**Comment by csantero** [comment]
Thanks!

@SphtKr LGTM?

**Comment by SphtKr** [comment]
Merged and pushed to NuGet as 0.3.0-pre-2

**Comment by SphtKr** [comment]
Yes we should unify this function with the `Attribute` serialization (formerly `Primitive`) functions.

**Comment by karlguillotte** [comment]
Thanks @SphtKr !

**Pull request merged**
